markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title
regeneration: true
lsi: true
exclude: README.textile Rakefile
tag_title_prefix: 'Tag: '
base_url: http://localhost:4000
title: ldw5258
post_types:
  - portfolio
server: true
